---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "ibeer-backend"
  namespace: "default"
  labels:
    app: "ibeer-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "ibeer-backend"
  template:
    metadata:
      labels:
        app: "ibeer-backend"
    spec:
      containers:
      - name: "ibeer-backend-sha256"
        image: "gcr.io/ovg-training/github.com/oliviervg1/ibeer-backend@sha256:f026eb56ee90a950bd87b276f45bd96093fbf0b8f9e92d2cc2a26d505110ac5f"

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ibeer-backend-hpa"
  namespace: "default"
  labels:
    app: "ibeer-backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ibeer-backend"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ibeer-backend-service"
  namespace: "default"
  labels:
    app: "ibeer-backend"
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: "ibeer-backend"
  type: "ClusterIP"
